### ISSUE TITLE
Feature Request: add support for /api/v1/system/initialize

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/go-api-sdk-jamfpro#604]
## Description

Adding support for `/api/v1/system/initialize` will allow terraform to set up a Jamf Pro server if it has not been initialized.

Related to #603 

<https://developer.jamf.com/jamf-pro/reference/post_v1-system-initialize>

**Comment by ShocOne** [comment]
added in release v1.16.0 with examples
