### ISSUE TITLE
Feature Request: add support for /api/v1/cloud-idp

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/go-api-sdk-jamfpro#605]
## Description

Adding support for `/api/v1/cloud-idp` will allow to manage cloud identity providers informations in other settings in Jamf Pro. For exemple to add a directory service group account we need to know the ID of the cloud identity configuration.

<https://developer.jamf.com/jamf-pro/reference/get_v1-cloud-idp>

**Comment by ShocOne** [comment]
added some of the endpoints from this within release v1.16.0 with examples. please could you confirm if the right ones are covered ? my lab jamf pro instance is not currently integrated with an IDP to test. thanks

**Comment by ecanault** [comment]
Hi @ShocOne 

It seems OK.
Here is the result for `GetCloudIdentityProviders.go`:

```
Cloud Identity Providers:
 {
    "totalCount": 3,
    "results": [
        {
            "id": "1001",
            "displayName": "LDAP G Suite (netopie.com)",
            "enabled": false,
            "providerName": "GOOGLE"
        },
        {
            "id": "1005",
            "displayName": "LDAP Azure (netopie.fr)",
            "enabled": true,
            "providerName": "AZURE"
        },
        {
            "id": "1009",
            "displayName": "LDAP Azure (netopie.net)",
            "enabled": true,
            "providerName": "AZURE"
        }
    ]
}
```

And the result for `GetCloudIdentityProviderConfigurationByID.go`:

```
Cloud Identity Provider (ID: 1005):
{
    "id": "1005",
    "displayName": "LDAP Azure (netopie.fr)",
    "providerName": "AZURE"
}
```

Thanks a lot 🙂
Emmanuel

**Comment by ShocOne** [comment]
Great. Thanks for confirming. I'll close the ticket. Thanks.
