### ISSUE TITLE
Feature Request: add support for /api/v4/enrollment and /api/v3/enrollment/access-groups

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/go-api-sdk-jamfpro#606]
## Description

Adding support for `/api/v4/enrollment` and `/api/v3/enrollment/access-groups` will allow to manage *User-initiated enrollment* settings in Jamf Pro.

May be linked to #605 for cloud identity group access.

<https://developer.jamf.com/jamf-pro/reference/get_v2-enrollment>
<https://developer.jamf.com/jamf-pro/reference/post_v2-enrollment-access-groups>
(documentation does not seem up to date as URL don't reflect the current API versions)

**Comment by ShocOne** [comment]
added in release v1.16.0 with examples
